
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 878495
	#The name of the modpack
	modpackName = "Valhelsia 6"
	#The version of the modpack
	modpackVersion = "6.1.0-pre2"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

